deny missing docs in ir and opt modules
fabianschuiki/llhd pull request #137
Opened 2020-08-31 04:13 UTC by azarmadr

i thought this would be easiest way to dive into llhd. and i am only doing it on weekends.

2020-08-31 14:09 UTC, fabianschuiki commented
This is an excellent idea, thanks! Do you want to have this merged now, or will you add additional commits later on?

2020-08-31 14:09 UTC, fabianschuiki approved these changes

2020-09-01 03:47 UTC, azarmadr commented
i still have ir module to do
i am new to any open source project involvement
can be merged now i guess?
thanks

2020-09-01 16:19 UTC, fabianschuiki commented
In that case, let me change the PR to a draft such that you can continue committing changes. As soon you feel the changes are done and `ir` and `opt` work with `deny(missing_docs)`, we merge the PR :smile:!

2020-09-09 11:20 UTC, azarmadr commented
getting a `missing document for a variant` for opcode enum in llhd::ir::inst

2020-09-09 20:33 UTC, fabianschuiki requested changes
Just a minor comment with the `sig` instruction doc, then things should be ready to merge. Thanks!

2020-09-09 20:33 UTC, fabianschuiki commented on doc/LANGUAGE.md
> +- `value` is the value to be assigned to the selected field, elements, or bits. Its type must correspond to a single field, element, or bit in case of the `insert element` variant, or an array or int
Nice catch

2020-09-09 20:33 UTC, fabianschuiki commented on examples/builder.rs
> +        let v2 = builder.ins().const_int((1, 1));
Cool, thanks for fixing these.

2020-09-09 20:33 UTC, fabianschuiki commented on src/ir/inst.rs
> +    /// Creates sig instruction to instantiates a proces or entity
I think this should read:
```suggestion
    /// Creates sig instruction to allocate a signal
```

2020-09-09 20:36 UTC, fabianschuiki commented
By the way: How about adding `#![deny(missing_docs)]` to `src/ir/mod.rs`? Or at least in those submodules where you have added the missing documentation?

2020-09-10 08:31 UTC, azarmadr commented
> 
> 
> By the way: How about adding `#![deny(missing_docs)]` to `src/ir/mod.rs`? Or at least in those submodules where you have added the missing documentation?

regarding that, getting a `missing document for a variant` for opcode enum in `llhd::ir::inst`
should i skip it?

2020-09-10 11:56 UTC, fabianschuiki commented
> regarding that, getting a `missing document for a variant` for opcode enum in `llhd::ir::inst`
In that case I would suggest to add `#[allow(missing_docs)]` to the `pub enum Opcode` in order to skip it, as you suggest :+1:!

2020-09-12 07:25 UTC, azarmadr commented
i have also added `[allow(missing_docs)]` to some structures which didn't need their fields explaining.
this concludes ir module

2020-09-14 19:26 UTC, fabianschuiki approved these changes
Looks good to me, thanks! Merging :+1:

2020-09-14 19:26 UTC, merged